starting_assumptions = ['0. Starting Assumptions'
                             'Development Timeline',
                             'Lot Area',
                             'Existing Building Floor Area',
                             'Residential Zoning Floor Area',
                             'Commercial Zoning Floor Area',
                             'Manufacturing Zoning Floor Area',
                             'AirRights Sq.Ft.',
                             'Total Gross Zoning Floor Area',
                             'Innacuracy Factor',
                             'Innacuracy Floor Loss +/-',
                             'Net Loss Factor',
                             'Total Net Zoning Floor Area',
                             ]

development = ['A. Develoment Costs',
                    'Residential Cost',
                    'Commercial Cost',
                    'Manufacturing Cost',
                    'Hard Cost',
                    'Soft Cost',
                    'Land Cost',
                    'Existing Building Purchase',
                    'Land Purchase',
                    'Residential Cost',
                    'Commercial Cost',
                    'Manufacturing Cost',
                    'Air Rights Purchase',
                    'Hard Cost',
                    'Soft Cost',
                    'Total Development Cost'
                    ]

capital = ['B. Capital Structure',
                         'Debt',
                         'Equity',
                         'Debt Service'
                         ]

residential = ['C. Projected Residential Proceeds',
                       'Common Area and Circulation',
                       'Net Residential Area',
                       'Avrg Market Rate Unit Size',
                       'Aproximate Units',
                       'Market Rate Rent',
                       'Residential Vacancy Rate',
                       'Income/Expense Escalation',
                       'Total Residential Income',
                       'Total Residential Vacancy',
                       '',
                       'Residential Expenses',
                       'Operational Expenses/SF',
                       'Real Estate Taxes/SF',
                       'Replacement Reserve/SF',
                       '',
                       'Total Operational Expenses',
                       'Total Real Estate Taxes',
                       'Total Replacement Reserve',
                       '',
                       'Depreciation',
                       'Residential Depreciation in yrs',
                       'Total Cost Residential',
                       'Residential Depreciation',
                       ]

commercial = ['D. Projected Commercial Proceeds',
                       'Common Area and Circulation',
                       'Net Commercial Area',
                       'Avrg Market Rate Unit Size',
                       'Aproximate Units',
                       'Market Rate Rent',
                       'Commercial Vacancy Rate',
                       'Income/Expense Escalation',
                       'Total Commercial Income',
                       'Total Commercial Vacancy',
                       '',
                       'Commercial Expenses',
                       'Operational Expenses/SF',
                       'Real Estate Taxes/SF',
                       'Replacement Reserve/SF',
                       '',
                       'Total Operational Expenses',
                       'Total Real Estate Taxes',
                       'Total Replacement Reserve',
                       '',
                       'Depreciation',
                       'Commercial Depreciation in yrs',
                       'Total Cost Commercial',
                       'Commercial Depreciation',
                       ]

manufacturing = ['E. Projected Manufacturing Proceeds',
                       'Common Area and Circulation',
                       'Net Manufacturing Area',
                       'Avrg Market Rate Unit Size',
                       'Aproximate Units',
                       'Market Rate Rent',
                       'Manufacturing Vacancy Rate',
                       'Income/Expense Escalation',
                       'Total Manufacturing Income',
                       'Total Manufacturing Vacancy',
                       '',
                       'Manufacturing Expenses',
                       'Operational Expenses/SF',
                       'Real Estate Taxes/SF',
                       'Replacement Reserve/SF',
                       '',
                       'Total Operational Expenses',
                       'Total Real Estate Taxes',
                       'Total Replacement Reserve',
                       '',
                       'Depreciation',
                       'Manufacturing Depreciation in yrs',
                       'Total Cost Manufacturing',
                       'Manufacturing Depreciation',
                       ]

rates = ['F. Other Rates',
              'Annual Increase in Expenses',
              'Annual Public Subsidy Increase',
              'Cap Rate @ Sale',
              'Sales Expenses',
              'Ordinary Income Tax',
              'Depreciation Recapture',
              'Capital Gains Tax',
              'Discount Rate',
              'Interest Rate',
              'Constant Rate',
              ]

totals = ['G. Totals',
          'Total Residential Income',
          'Total Commercial Income',
          'Total Manufacturing Income',
          'Total Gross Incomes',
          '',
          'Total Residential Vacancy',
          'Total Commercial Vacancy',
          'Total Manufacturing Vacancy',
          'Total Vacancy',
          '',
          'Total Property Operational Expenses',
          'Total Property Real Estate Taxes',
          'Total Property Replacement Reserve',
          'Total Expenses',
          '',
          'Residential Depreciation',
          'Commercial Depreciation',
          'Manufacturing Depreciation',
          'Total Depreciation Cost'
          ]